### ISSUE TITLE
Issue creating more than 16 pins

### ISSUE THREAD

**Issue by cakeslob** [Expatria-Technologies/remora-flexi-hal#2]
Hey, Ive been working on my nucleo static config thing using the F446RE, using flexi-hal as my baseline, but these issues Im getting with flexi-hal also. 

I cant create more than 16 pins in total, if I compile with the board_config for flexihal, or any other config with more than 16 pins total, the board (I think) is getting a config error while creating the 16th pin and just loops over and over. The issue never came up for me before because Ive only been using 15 pins up until now.

**Comment by andrewmarles** [comment]
You may want to check in on our Discord channel for something like this as the discussion would be a bit more dynamic.

I don't think there has been much testing with configs beyond what we have posted for Flexi.  At a minimum you'd need to post the config that you are trying to use.

**Comment by cakeslob** [comment]
Alright cool, Ill check out the channel this evening. Maybe I just need a sanity check. 

The only thing I changed was replace "flexihal" with "nucleo_f446"

Im just trying to compile a vanilla config, with the flexi-hal repo, which crashes after the 15th pin is created in loadmodule(), and then just loops. 
https://github.com/Expatria-Technologies/remora-flexi-hal/blob/master/Firmware/FirmwareSource/Remora-OS5/TARGET_FLEXIHAL/board_config.h

This is my working config, this one does work and creates all the pins, but nothing more than this amount of pins. , if you add 1 more pin, it will not finish loadmodules(). 
https://github.com/cakeslob/Remora/blob/nucleo_static/Firmware/FirmwareSource/Remora-OS6/TARGET_NUCLEO_F446RE/board_config.h

everything compiles fine, its when Its running on the board, it never makes it into start state or idle state, it never completes loadmodules()

**Comment by cakeslob** [comment]
Sorry about all this, 
https://github.com/cakeslob/Remora/blob/static_config/Firmware/FirmwareSource/Remora-OS5/TARGET_SPIDER/board_config.h
Looks like I have been making +16 pin configs this whole time. This appears to somehow be an issue with the nucleo specifically, and nothing to do with flexi-hal.
Thanks for the help, your patience was appreciated.
